@WebApi_HostAddress = http://localhost:5137


POST {{WebApi_HostAddress}}/order/
Content-Type: application/json

{
  "orderId": "4",
  "itemId": "A",
  "itemQuantity": 1
}

###

GET {{WebApi_HostAddress}}/order/1

###

POST {{WebApi_HostAddress}}/shipment/
Content-Type: application/json

{
  "order_id": "1",
  "location": "Lost",
  "timestamp": 1714490644
}

